apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-cli-deployment
  labels:
    app: temporal-cli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temporal-cli
  template:
    metadata:
      labels:
        app: temporal-cli
    spec:
      containers:
      - name: temporal-cli-container
        image: tr920/temperol-server:1.0
        ports:
        - containerPort: 8233
        - containerPort: 7233
        args: ["temporal", "server", "start-dev", "--ip", "0.0.0.0"] # 確保服務綁定到 0.0.0.0
