apiVersion: v1
kind: Service
metadata:
  name: temporal
spec:
  selector:
    app: temporal
  ports:
    - name: http
      protocol: TCP
      port: 8233
      targetPort: 8233
    - name: server
      protocol: TCP
      port: 7233
      targetPort: 7233
  type: ClusterIP
