apiVersion: v1
kind: Service
metadata:
  name: temporal
spec:
  selector:
    app: temporal
  ports:
    - name: http
      protocol: TCP
      port: 8233
      targetPort: 8233
      nodePort: 30000  # 隨意指定一個未使用的 NodePort
  type: NodePort