apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-compiler-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-compiler-api
  template:
    metadata:
      labels:
        app: java-compiler-api
    spec:
      containers:
        - name: java-compiler-api
          image: tr920/java-compiler-api:3.4.1
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: java-compiler-api
spec:
  type: LoadBalancer
  selector:
    app: java-compiler-api
  ports:
    - protocol: TCP
      port: 5566
      targetPort: 8080


